modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/smashingmods/alchemistry/issues"

[[mods]]
modId="alchemistry"
version="${file.jarVersion}"
displayName="Alchemistry"
logoFile="alchemistry-logo.png"
authors="SmashingMods"
description='''
Alchemistry is a tech mod, inspired by the classic Minechem, that allows you to decompose items into their constituent elements, then recombine them to create new items.
'''

[[dependencies.alchemistry]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alchemistry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.19.4)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alchemistry]]
    modId="chemlib"
    mandatory=true
    versionRange="[1.19.3-2.0.17,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alchemistry]]
    modId="alchemylib"
    mandatory=true
    versionRange="[1.19.3-1.0.22,)"
    ordering="NONE"
    side="BOTH"
